image_width: 1440
image_height: 1080
camera_name: hk_left
camera_matrix:
  rows: 3
  cols: 3
  data: [1793.45495,    0.     ,  761.63528,
            0.     , 1791.83362,  551.58477,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.079407, 0.113988, -0.000268, -0.000251, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1774.34851,    0.     ,  761.46581,    0.     ,
            0.     , 1778.79749,  551.0661 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
